// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2PgjH5pUAzjkscre7ePINXEJS_jYYO8',
    appId: '1:61504972008:web:4014334387898533da555d',
    messagingSenderId: '61504972008',
    projectId: 'student-ai-assistant-dc9a8',
    authDomain: 'student-ai-assistant-dc9a8.firebaseapp.com',
    storageBucket: 'student-ai-assistant-dc9a8.firebasestorage.app',
    measurementId: 'G-VV3BLDDPYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4aYgxDzy6qEe0I43PV7qzUHPKe4J-z4',
    appId: '1:61504972008:android:08382ee656f3719cda555d',
    messagingSenderId: '61504972008',
    projectId: 'student-ai-assistant-dc9a8',
    storageBucket: 'student-ai-assistant-dc9a8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2PgjH5pUAzjkscre7ePINXEJS_jYYO8',
    appId: '1:61504972008:web:cc5e70f241a44b6dda555d',
    messagingSenderId: '61504972008',
    projectId: 'student-ai-assistant-dc9a8',
    authDomain: 'student-ai-assistant-dc9a8.firebaseapp.com',
    storageBucket: 'student-ai-assistant-dc9a8.firebasestorage.app',
    measurementId: 'G-ZNP5VHYXCE',
  );
}
