/// An immutable snapshot of the dashboard presentation state.
class DashboardState {
  /// Creates a [DashboardState] with the given values.
  const DashboardState({
    this.projects = const <DashboardProject>[],
    this.aiInsight = '',
  });

  /// Creates the initial dashboard state with empty data.
  ///
  /// Projects and AI insights are initially empty. They will be populated
  /// when real data is loaded from Firestore or generated by the AI service.
  factory DashboardState.initial() => const DashboardState();

  /// Projects displayed in the projects card.
  ///
  /// Empty by default. Projects will be loaded from the user's profile or
  /// a dedicated projects repository when implemented.
  final List<DashboardProject> projects;

  /// AI-generated insight for the day.
  ///
  /// Empty by default. Insights will be generated by the AI planner service
  /// based on the user's schedule, tasks, and goals when implemented.
  final String aiInsight;

  /// Returns a copy of this state with the given fields replaced.
  DashboardState copyWith({
    List<DashboardProject>? projects,
    String? aiInsight,
  }) {
    return DashboardState(
      projects: projects ?? this.projects,
      aiInsight: aiInsight ?? this.aiInsight,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DashboardState &&
            other.projects == projects &&
            other.aiInsight == aiInsight;
  }

  @override
  int get hashCode => Object.hash(
    projects,
    aiInsight,
  );
}

// ---------------------------------------------------------------------------
// Value types
// ---------------------------------------------------------------------------

/// A project entry displayed in the dashboard projects card.
class DashboardProject {
  /// Creates a [DashboardProject].
  const DashboardProject({
    required this.name,
    required this.tag,
    this.progress = 0.0,
  });

  /// The project name shown to the user.
  final String name;

  /// A short category tag (e.g. 'Dev', 'Study', 'Health').
  final String tag;

  /// Progress from 0.0 to 1.0 (0% to 100%).
  final double progress;

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DashboardProject &&
            other.name == name &&
            other.tag == tag &&
            other.progress == progress;
  }

  @override
  int get hashCode => Object.hash(name, tag, progress);
}
