import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';
import '../../../authentication/presentation/providers/auth_providers.dart';
import '../../domain/entities/calendar_event_entity.dart';
import '../providers/calendar_providers.dart';

/// Daily calendar of fixed commitments. Planner sessions are displayed on the
/// plan page; events here define the unavailable time that plan must respect.
class CalendarPage extends ConsumerStatefulWidget { const CalendarPage({super.key}); @override ConsumerState<CalendarPage> createState() => _CalendarPageState(); }
class _CalendarPageState extends ConsumerState<CalendarPage> {
  DateTime _day = DateUtils.dateOnly(DateTime.now());
  String? get _uid => ref.read(authControllerProvider).user?.id;
  @override void initState() { super.initState(); WidgetsBinding.instance.addPostFrameCallback((_) => _load()); }
  void _load() { final uid = _uid; if (uid != null) ref.read(calendarControllerProvider.notifier).loadEvents(uid, start: _day, end: _day.add(const Duration(days: 1))); }
  void _changeDay(int amount) { setState(() => _day = _day.add(Duration(days: amount))); _load(); }
  Future<void> _edit([CalendarEventEntity? event]) async {
    final created = await showModalBottomSheet<CalendarEventEntity>(context: context, isScrollControlled: true, builder: (_) => _EventEditor(event: event, initialDay: _day));
    final uid = _uid; if (created != null && uid != null) await ref.read(calendarControllerProvider.notifier).saveEvent(uid, created);
  }
  @override Widget build(BuildContext context) { final state = ref.watch(calendarControllerProvider); final events = state.events.where((e) => e.overlaps(_day, _day.add(const Duration(days: 1)))).toList(); return Scaffold(appBar: AppBar(title: const Text('Calendar'), actions: [IconButton(onPressed: () => _changeDay(-1), icon: const Icon(Icons.chevron_left)), TextButton(onPressed: () { setState(() => _day = DateUtils.dateOnly(DateTime.now())); _load(); }, child: Text(MaterialLocalizations.of(context).formatMediumDate(_day))), IconButton(onPressed: () => _changeDay(1), icon: const Icon(Icons.chevron_right))]), body: state.isLoading ? const Center(child: CircularProgressIndicator()) : events.isEmpty ? const Center(child: Text('No events today. Add commitments so your plan has real boundaries.')) : ListView.separated(padding: const EdgeInsets.all(16), itemCount: events.length, separatorBuilder: (_, __) => const SizedBox(height: 8), itemBuilder: (_, i) { final event = events[i]; return Card(child: ListTile(leading: Icon(event.isFlexible ? Icons.drag_indicator : Icons.event_busy), title: Text(event.title), subtitle: Text('${TimeOfDay.fromDateTime(event.startTime).format(context)} – ${TimeOfDay.fromDateTime(event.endTime).format(context)}${event.recurrence == CalendarRecurrence.none ? '' : ' · ${event.recurrence.name}'}'), trailing: IconButton(icon: const Icon(Icons.delete_outline), onPressed: () { final uid = _uid; if (uid != null) ref.read(calendarControllerProvider.notifier).deleteEvent(uid, event.id); }), onTap: () => _edit(event))); }), floatingActionButton: FloatingActionButton(onPressed: () => _edit(), child: const Icon(Icons.add))); }
}

class _EventEditor extends StatefulWidget { const _EventEditor({this.event, required this.initialDay}); final CalendarEventEntity? event; final DateTime initialDay; @override State<_EventEditor> createState() => _EventEditorState(); }
class _EventEditorState extends State<_EventEditor> { late final TextEditingController _title; late DateTime _start; late DateTime _end; late bool _flexible; late CalendarRecurrence _recurrence;
  @override void initState() { super.initState(); final e = widget.event; _title = TextEditingController(text: e?.title ?? ''); _start = e?.startTime ?? widget.initialDay.add(const Duration(hours: 9)); _end = e?.endTime ?? _start.add(const Duration(hours: 1)); _flexible = e?.isFlexible ?? false; _recurrence = e?.recurrence ?? CalendarRecurrence.none; }
  Future<void> _time(bool start) async { final selected = await showTimePicker(context: context, initialTime: TimeOfDay.fromDateTime(start ? _start : _end)); if (selected != null) setState(() { final value = DateTime(_start.year, _start.month, _start.day, selected.hour, selected.minute); if (start) _start = value; else _end = value; }); }
  @override Widget build(BuildContext context) => Padding(padding: EdgeInsets.fromLTRB(24, 24, 24, MediaQuery.viewInsetsOf(context).bottom + 24), child: Column(mainAxisSize: MainAxisSize.min, children: [Text(widget.event == null ? 'Add event' : 'Edit event', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 16), TextField(controller: _title, autofocus: true, decoration: const InputDecoration(labelText: 'Title', border: OutlineInputBorder())), const SizedBox(height: 8), Row(children: [Expanded(child: OutlinedButton(onPressed: () => _time(true), child: Text('Start ${TimeOfDay.fromDateTime(_start).format(context)}'))), const SizedBox(width: 8), Expanded(child: OutlinedButton(onPressed: () => _time(false), child: Text('End ${TimeOfDay.fromDateTime(_end).format(context)}')))]), SwitchListTile(contentPadding: EdgeInsets.zero, title: const Text('Flexible event'), subtitle: const Text('Flexible events do not block the planner.'), value: _flexible, onChanged: (v) => setState(() => _flexible = v)), DropdownButtonFormField(value: _recurrence, decoration: const InputDecoration(labelText: 'Repeat'), items: CalendarRecurrence.values.map((v) => DropdownMenuItem(value: v, child: Text(v.name[0].toUpperCase() + v.name.substring(1)))).toList(), onChanged: (v) => setState(() => _recurrence = v!)), const SizedBox(height: 16), FilledButton(onPressed: _title.text.trim().isEmpty || !_end.isAfter(_start) ? null : () => Navigator.pop(context, CalendarEventEntity(id: widget.event?.id ?? const Uuid().v4(), title: _title.text.trim(), startTime: _start, endTime: _end, isFlexible: _flexible, recurrence: _recurrence, createdAt: widget.event?.createdAt ?? DateTime.now(), updatedAt: DateTime.now())), child: const Text('Save'))]));
  @override void dispose() { _title.dispose(); super.dispose(); }
}
